name: party-song-guess
services:
  server:
    container_name: party-song-guess-server
    build: ../app/server
    ports:
      - "3000:3000"
    volumes:
      - ../app/server:/app/server
    env_file:
      - .env
    command: node index.js

  client:
    container_name: party-song-guess-client
    build: ../app/client
    ports:
      - "5173:5173"
    volumes:
      - ../app/client:/app/client
      - /app/client/node_modules
    command: npm run dev
    depends_on:
      - server
